[package]
name = "rssget"
version = "0.1.0"
authors = ["Matias HeikkilÃ¤ <matias.heikkila@futurice.com>"]

[dependencies]
reqwest = "^0.9.2"
clap = "^2.32"
regex = "1.0.5"
rust-crypto = "0.2.36"
byteorder = "1.2.6"
hex = "0.3.1"
